<table width="100%" border="0" align="center" id="navigation">
<tr>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][1]); ?><?php print($main_navigation['sub_name'][1]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][2]); ?><?php print($main_navigation['sub_name'][2]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][3]); ?><?php print($main_navigation['sub_name'][3]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][4]); ?><?php print($main_navigation['sub_name'][4]); ?></a></td>
</tr>
<tr>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][5]); ?><?php print($main_navigation['sub_name'][5]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][6]); ?><?php print($main_navigation['sub_name'][6]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][7]); ?><?php print($main_navigation['sub_name'][7]); ?></a></td>
<td class="navigation"><?php $htmlClass->linkPath($main_navigation['path'][8]); ?><?php print($main_navigation['sub_name'][8]); ?></a></td>
</tr>
</table>
