<?php /* CONTAINER */ ?>
<div id="container">
<?php /* CONTAINER */ ?>

	<div class="title-nomargin">MENU</div>
	<section id="list-menu">
		<ul>
			<li><a href="/news/">お知らせ</a></li>
			<li><a href="/information/guide/">遊び方ガイド</a></li>
			<li><a href="/tutorial/">チュートリアル</a></li>
			<li><a href="/information/help/">ヘルプ</a></li>
		</ul>
	</section>

<?php /* CONTAINER */ ?>
</div>
<?php /* CONTAINER */ ?>
