<?php
/************************************************
**
**	ERROR
**
************************************************/
?>
<?php $htmlClass->getMobileTitle("error",$title_background,$title_color,$font_size); ?>
<?php print($spacer); ?>
<?php print($contents_table); ?>
<div style="text-align: center; color: #FF0000;">
<?php print($error); ?><br />
</div>
<?php print($table_end); ?>
<?php print($hr); ?>
