<?php /* CONTAINER */ ?>
<div id="container">
<?php /* CONTAINER */ ?>

	<div class="title">ガチャエラー</div>

	<div class="container-box">
		<div id="warning">
			<?php print($errormessage); ?>
		</div>
		<div class="image-center"><a href="/gacha/"><img src="/images/pc/button/button-return.png" style="width: 250px; height: 60px;" /></a></div>
	</div>


<?php /* CONTAINER */ ?>
</div>
<?php /* CONTAINER */ ?>