<?php /* CONTAINER */ ?>
<div id="container">
<?php /* CONTAINER */ ?>

	<div class="title">エラー</div>

	<div class="container-box">
		<div id="warning">
			<img src="/images/character/tutorial-finish.png" border="0" /><br />
            <br />
			<?php print($error); ?>
		</div>
		<div class="image-center"><a href="<?php print($return_path); ?>" target="_top"><img src="/images/smart/button/button-return-top.png" style="width: 250px; height: 60px;" /></a></div>
	</div>

<?php /* CONTAINER */ ?>
</div>
<?php /* CONTAINER */ ?>