<?php /* CONTAINER */ ?>
<div id="container">
<?php /* CONTAINER */ ?>

<script src="/common/js/error.script.js" type="text/javascript" ></script>
<div id="error-result">

	<section id="error-result-area">
		<div id="error-result-box">
			<div class="error-result-title"><img src="/images/smart/title/title-error.png" /></div>
			<div class="error-result-contents">
				<?php print($errormessage); ?>
			</div>
			<div class="image-center"><a href="<?php print($return_path); ?>"><img src="/images/smart/button/button-return.png" style="width: 250px; height: 60px;" /></a></div>
		</div>
	</section>

</div>

<?php /* CONTAINER */ ?>
</div>
<?php /* CONTAINER */ ?>