<?php /* CONTAINER */ ?>
<div id="container">
<?php /* CONTAINER */ ?>

	<?php if($data['id'] == "ie"){ ?>

		<div class="title">IEをお使いの方</div>

		<section id="news">
			<div id="news-body">
				IEをお使いの場合、正常にゲームと接続できない場合が御座います。<br />
				当ゲームではGoogle Chromeを推奨しておりますが、<br />
				『どうしてもIEでゲームがしたい！』<br />
				と言う方は下記の通り、ブラウザの設定を変更して頂くことでゲームができるようになる場合があります。<br />
				<br />
				・１ IEの『ツール』→『インターネットオプション』を開く<br />
				・２ 『プライバシー』タブをクリック<br />
				・３ 設定項目の『詳細設定』をクリック<br />
				・４ 『自動Cookie処理を上書きする』にチェックをつける<br />
				・５ 『常にセッションCookieを許可する』にチェックをつける<br />
				・６ OKをクリック<br />
				・７ 適応を押し、ブラウザを立ち上げ直す。<br />
				・８ きゃばへるスタート！<br />
				<br />
				<br />
				<span style="color: #FF0000;">
				※こちらは100%稼動を保障するものでは御座いません。<br />
				また、会員様の任意で行って頂くため、設定変更における不具合・トラブル等は当ゲームでは一切責任を負いかねますことを予めご了承下さいませ。
				</span>
				<br />
				<br />
			</div>
		</section>


		<div class="image-center"><a href="<?php print(APP_URL); ?>" target="_top"><img src="/images/smart/button/button-return.png" style="width: 250px; height: 60px;" /></a></div>

	<?php } ?>


<?php /* CONTAINER */ ?>
</div>
<?php /* CONTAINER */ ?>
